[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytincture"
version = "0.9.4"
description = "UI Builder"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Your Name", email = "schapman1974@gmail.com" }
]
dependencies = [
    "aiofiles==24.1.0",
    "fastapi==0.115.12",
    "upstash-redis>=1.2.0",
    "pyyaml==6.0.2",
    "requests==2.32.3",
    "uvicorn==0.34.0",
    "wheel==0.45.1",
    "js==1.0",
    "pyodide-py==0.27.3",
    "authlib==1.5.1",
    "python-dotenv==1.0.1",
    "aioredis==2.0.1",
    "pytest==8.3.5"
]

[project.urls]
Homepage = "https://github.com/pytincture/pytincture"

[tool.setuptools.packages]
find = {}
